### ISSUE TITLE
Scraper ccrashing?

### ISSUE THREAD

**Issue by gerroon** [Miosame/flatline#5]
`docker logs -f flatline_scraper_1 `

```
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: Access denied for user 'flatlineUSR'@'localhost' (using password: YES)
    at Packet.asError (/usr/src/app/node_modules/mysql2/lib/packets/packet.js:712:17)
    at ClientHandshake.execute (/usr/src/app/node_modules/mysql2/lib/commands/command.js:28:26)
    at Connection.handlePacket (/usr/src/app/node_modules/mysql2/lib/connection.js:417:32)
    at PacketParser.Connection.packetParser.p [as onPacket] (/usr/src/app/node_modules/mysql2/lib/connection.js:75:12)
    at PacketParser.executeStart (/usr/src/app/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.Connection.stream.on.data (/usr/src/app/node_modules/mysql2/lib/connection.js:82:25)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
Emitted 'error' event at:
    at Connection._notifyError (/usr/src/app/node_modules/mysql2/lib/connection.js:221:12)
    at ClientHandshake.Connection.handshakeCommand.on.err (/usr/src/app/node_modules/mysql2/lib/connection.js:114:14)
    at ClientHandshake.emit (events.js:203:15)
    at ClientHandshake.execute (/usr/src/app/node_modules/mysql2/lib/commands/command.js:33:14)
    at Connection.handlePacket (/usr/src/app/node_modules/mysql2/lib/connection.js:417:32)
    [... lines matching original stack trace ...]
    at addChunk (_stream_readable.js:288:12)
```

**Comment by gerroon** [comment]
all others are running fine

```
2020-01-22T04:10:06.144840Z 0 [Warning] CA certificate ca.pem is self signed.
2020-01-22T04:10:06.147552Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
2020-01-22T04:10:06.147614Z 0 [Note] IPv6 is available.
2020-01-22T04:10:06.147628Z 0 [Note]   - '::' resolves to '::';
2020-01-22T04:10:06.147652Z 0 [Note] Server socket created on IP: '::'.
2020-01-22T04:10:06.190751Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
2020-01-22T04:10:06.191929Z 0 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
2020-01-22T04:10:06.191954Z 0 [Warning] 'user' entry 'mysql.session@localhost' ignored in --skip-name-resolve mode.
2020-01-22T04:10:06.191964Z 0 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
2020-01-22T04:10:06.191989Z 0 [Warning] 'db' entry 'performance_schema mysql.session@localhost' ignored in --skip-name-resolve mode.
2020-01-22T04:10:06.191994Z 0 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
2020-01-22T04:10:06.192009Z 0 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
2020-01-22T04:10:06.193970Z 0 [Warning] 'tables_priv' entry 'user mysql.session@localhost' ignored in --skip-name-resolve mode.
2020-01-22T04:10:06.193985Z 0 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
2020-01-22T04:10:06.200267Z 0 [Note] Event Scheduler: Loaded 0 events
2020-01-22T04:10:06.200457Z 0 [Note] mysqld: ready for connections.
Version: '5.7.25'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
```

**Comment by Miosame** [comment]
That happens only if the range is entered wrong, could you tell me what you entered for `SCAN_RANGE`?

**Comment by Miosame** [comment]
Oh nevermind: `Error: Access denied for user 'flatlineUSR'@'localhost' (using password: YES)`

it was an issue due to the bug that got fixed just ~15 seconds ago, please re-download the repo deleting the old folder.

**Comment by Miosame** [comment]
My bad, will push the update that fixes this too in a second, it was due to the change earlier.

**Comment by gerroon** [comment]
Not sure this is a different issue

```
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND mysql mysql:3306
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
Emitted 'error' event at:
    at Connection._notifyError (/usr/src/app/node_modules/mysql2/lib/connection.js:221:12)
    at Connection._handleFatalError (/usr/src/app/node_modules/mysql2/lib/connection.js:156:10)
    at Connection._handleNetworkError (/usr/src/app/node_modules/mysql2/lib/connection.js:169:10)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)


```

**Comment by Miosame** [comment]
@gerroon I've did bunch of quick fixes on master, instead of testing locally first, learned my lesson. I have reverted those quick changes - will test it shortly myself first and confirm if it is indeed fixed now after reverting back to the working state it originally was.

**Comment by gerroon** [comment]
No porblem take ur time. I am wiling to test it when you want me to.

**Comment by Miosame** [comment]
@gerroon tested it now on my setup and seems to be working again, please test to confirm it works for you too

**Comment by gerroon** [comment]
```
Creating network "flatline_default" with the default driver                                                                                                                                                        
Creating flatline_mysql_1 ... error                                                                                                                                                                                
                                                                                                                                                                                                                   
ERROR: for flatline_mysql_1  Cannot start service mysql: driver failed programming external connectivity on endpoint flatline_mysql_1 (9ac9cc9deff0a6a714014f6470131ea489364fc4e119bf1c0649f00764f36dcb): Error sta
rting userland proxy: listen tcp 0.0.0.0:3306: bind: address already in use                                                                                                                                        
                                                                                                                                                                                                                   
ERROR: for mysql  Cannot start service mysql: driver failed programming external connectivity on endpoint flatline_mysql_1 (9ac9cc9deff0a6a714014f6470131ea489364fc4e119bf1c0649f00764f36dcb): Error starting userl
and proxy: listen tcp 0.0.0.0:3306: bind: address already in use
ERROR: Encountered errors while bringing up the project.
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
```

**Comment by Miosame** [comment]
@gerroon `tcp 0.0.0.0:3306: bind: address already in use` - yeah that's because of: https://github.com/Miosame/flatline/issues/7 - the setup currently assumes that you have :3306 free for the new spawned mysql container and the scraper to use.

I'll need to go through all things that need changes (some mentioned in #7) and test for other situations, e.g. an external database that already exists.

I'll commit a change probably tomorrow that'll allow you to just set a custom port for now, e.g. `DB_PORT_CUSTOM=3307`, that'll expose the new mysql container on port 3307 and make the scraper push to it too.

Once I implement #7 more cleanly, you could change over to it then or just stay with that solution, whatever you prefer by the time I implement it.

**Comment by gerroon** [comment]
No worries, as long as you do not crash my network or sell my dead body on the bitcoin market we are good. i will test it tomorrow.

**Comment by Miosame** [comment]
@gerroon decided to make the change already, can you test the branch if it works for you too? it worked just fine on my machine.

- Make sure to pull the new branch and not master:
`git clone --branch=add-db-port-config --depth=1 https://github.com/Miosame/flatline.git`

- then change in `.env`: `DB_PORT_CUSTOM` to be e.g. `DB_PORT_CUSTOM=3307`
- the rest is as usual

**Comment by gerroon** [comment]
Ok this seems to work I think, I have not tested it extensively but I do not see crashes. It would have been nice if the Mysql contaier was not exposed port wise though

**Comment by Miosame** [comment]
@gerroon awesome, if anything happens again, please open a new issue, thanks for testing and reporting the issue in the first place! I'll close this for now and regarding: `It would have been nice if the Mysql contaier was not exposed port wise though` - monitor #7 as that's where I'll close or post if it is possible, ideally I'd either have the scraper and mysql not exposed to the host network or have an option at the very least to switch over the remaining containers to be able to connect to an outside existing mysql container.
